import Head from 'next/head'
import ProductsCart from '../components/ProductsCart'
import { getAllProducts } from './api/productsApi'

export default function Home({ products }) {

	return (
		<div>
			<Head>
				<title>watch store</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<header></header>

			<main>
				<ProductsCart products={products} />
			</main>

			<footer></footer>
		</div>
	)
}

export async function getStaticProps() {
	const { data: products } = await getAllProducts()
	return {
		props: {
			products,
		},
	}
}
