import Head from 'next/head'
import ProductsList from '../components/ProductsList'
import { getAllProducts } from './api/productsApi'

export default function Home({ products }) {
	return (
		<div>
			<Head>
				<title>watch store</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className="flex justify-center h-full w-full">
				<ProductsList products={products} />
			</main>
		</div>
	)
}

export async function getStaticProps() {
	const { data: products } = await getAllProducts()
	return {
		props: {
			products,
		},
	}
}
