import axios from 'axios'
import Head from 'next/head'
import { getAllProducts } from './api/productsApi'

export default function Home({ data }) {
	console.log('Test data : ', data)

	const products = data.map((p) => p)
	console.log('Products : ', products)

	return (
		<div>
			<Head>
				<title>watch store</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className="text-blue-800 text-5xl bg-red-300">
				{products &&
					products.map((product) => {
						return (
							<div>
								<span>{product.attributes.brand.data.attributes.name}    </span>
								<span>{}</span>
								<span>{product.attributes.name}</span>
								<span>{product.attributes.price}</span>
								<br />
							</div>
						)
					})}
			</main>

			<footer></footer>
		</div>
	)
}

export async function getStaticProps() {
	const { data } = await getAllProducts()
	return {
		props: {
			data,
		},
	}
}
